[package]
name = "benchkit"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.1"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["cargo", "derive", "env"] }
rand = "0.9.0"
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
serde_yaml = "0.9.34"
serial_test = "3.2.0"
shellexpand = "3.1.0"
tempfile = "3.17.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
tokio-postgres = "0.7.13"
