---
# Benchkit home directory
home_dir: $HOME/.local/state/benchkit

# The directory intermediate built binaries will be saved to.
bin_dir: $HOME/.local/state/benchkit/binaries

# The directory containing benchkit patches
patch_dir: $HOME/.local/state/benchkit/patches

# The directory containing assumeutxo snapshots
snapshot_dir: $HOME/.local/state/benchkit/snapshots

# Database configuration
# Only required to use `db` commands
# database:
#
#   # postgres host
#   host: localhost
#
#   # postgres port
#   port: 5432
#
#   # database name
#   database: benchmarks
#
#   # postgres username
#   user: benchkit
#
#   # postgres password
#   password: benchcoin
